"""Rich fashion taxonomies for synthetic DeepFashion-expansion captions.
Generated from a parallel-agent brainstorm workflow; hand-reviewed. stdlib-only data module.
"""

FEMALE_GARMENTS = {
    "tops": [
        "a fitted ribbed turtleneck",
        "a silk camisole with thin straps",
        "a structured button-down shirt",
        "a flowy peasant blouse",
        "an off-the-shoulder top",
        "a cropped boxy tee",
        "a draped cowl-neck top",
        "a puff-sleeve blouse",
        "a halter-neck top",
        "a wrap top tied at the waist",
        "a sleeveless mock-neck shell",
        "a tie-front knotted blouse",
        "a fitted bodysuit",
        "a sheer chiffon blouse",
        "a graphic-print t-shirt",
        "a bardot smocked top",
        "a satin bustier top",
        "a Breton-stripe long-sleeve tee",
        "a linen tunic",
        "a corset-style lace-up top"
    ],
    "bottoms": [
        "high-waisted wide-leg trousers",
        "tailored cigarette pants",
        "high-rise straight-leg jeans",
        "a pleated midi skirt",
        "a denim mini skirt",
        "a flowing maxi skirt",
        "an A-line knee-length skirt",
        "wide-leg palazzo pants",
        "high-waisted paper-bag shorts",
        "faux-leather leggings",
        "a pencil skirt",
        "cropped flare jeans",
        "linen drawstring trousers",
        "a tiered ruffled skirt",
        "tailored culottes",
        "distressed boyfriend jeans",
        "a pleated tennis skirt",
        "satin slip skirt",
        "corduroy bootcut pants",
        "a wrap skirt"
    ],
    "dresses": [
        "a wrap dress",
        "a floral sundress",
        "a fitted bodycon dress",
        "a tiered boho maxi dress",
        "a slip dress",
        "a shirtdress",
        "an A-line skater dress",
        "a sweater dress",
        "a smocked midi dress",
        "a halter-neck cocktail dress",
        "a puff-sleeve tea dress",
        "a linen shift dress",
        "a pinafore dress",
        "a one-shoulder draped dress",
        "a denim button-front dress",
        "a cap-sleeve fit-and-flare dress",
        "a tiered chiffon prairie dress",
        "a ribbed knit bodycon dress"
    ],
    "outerwear": [
        "a tailored blazer",
        "a belted trench coat",
        "a cropped denim jacket",
        "an oversized wool overcoat",
        "a quilted puffer jacket",
        "a faux-fur coat",
        "a moto leather jacket",
        "a longline duster coat",
        "a double-breasted peacoat",
        "a utility field jacket",
        "a soft teddy borg coat",
        "a cropped bomber jacket",
        "a houndstooth wool cape",
        "a belted wrap coat",
        "a shearling-lined aviator jacket",
        "a lightweight anorak",
        "a tweed boucle jacket"
    ],
    "formal": [
        "a floor-length silk evening gown",
        "a sequined cocktail dress",
        "a tailored pantsuit",
        "a tea-length lace dress",
        "a one-shoulder satin gown",
        "a velvet wrap gown",
        "a beaded sheath dress",
        "an off-the-shoulder ballgown",
        "a tuxedo-style jumpsuit",
        "a chiffon empire-waist gown",
        "a strapless mermaid gown",
        "a draped Grecian column dress",
        "a brocade dinner suit",
        "a black crepe midi cocktail dress"
    ],
    "athletic": [
        "high-waisted compression leggings",
        "a racerback sports bra",
        "a cropped athletic tank",
        "a quarter-zip running pullover",
        "matching biker shorts and a crop top",
        "a pleated tennis dress",
        "a lightweight running windbreaker",
        "fleece-lined joggers",
        "a seamless workout bodysuit",
        "a moisture-wicking training tee",
        "a yoga wrap and high-rise leggings set",
        "an oversized gym hoodie",
        "a track jacket with side stripes"
    ],
    "knitwear": [
        "a chunky cable-knit sweater",
        "a fine merino crewneck jumper",
        "an oversized turtleneck sweater",
        "a cropped ribbed cardigan",
        "a longline duster cardigan",
        "a mohair balloon-sleeve sweater",
        "a knit polo top",
        "a fair-isle yoke sweater",
        "a ribbed knit twinset",
        "a slouchy off-shoulder knit",
        "a waffle-knit henley",
        "a fitted ribbed sweater dress",
        "a chenille V-neck pullover"
    ],
    "occasion": [
        "a satin bridesmaid dress",
        "a beaded flapper-style party dress",
        "a holiday velvet wrap dress",
        "an embroidered festival maxi dress",
        "a metallic lame mini dress",
        "a tulle-skirted prom gown",
        "a feather-trimmed cocktail dress",
        "a sequined party jumpsuit",
        "a draped cocktail jumpsuit",
        "an organza tea-party dress",
        "a sleek New Year's sequin gown"
    ]
}

MALE_GARMENTS = {
    "tops": [
        "a crisp white button-down shirt",
        "a fitted crewneck t-shirt",
        "an Oxford cloth dress shirt",
        "a short-sleeve camp collar shirt",
        "a striped rugby shirt",
        "a classic polo shirt",
        "a henley long-sleeve top",
        "a flannel plaid shirt",
        "a linen band-collar shirt",
        "a graphic-print tee",
        "a chambray work shirt",
        "a fitted V-neck tee",
        "a corduroy overshirt",
        "a knit polo shirt",
        "a relaxed boxy tee",
        "a denim western shirt"
    ],
    "bottoms": [
        "straight-leg dark wash jeans",
        "tailored chino trousers",
        "slim-fit dress trousers",
        "relaxed-fit cargo pants",
        "pleated wool suit trousers",
        "tapered joggers",
        "raw selvedge denim jeans",
        "knee-length tailored shorts",
        "corduroy trousers",
        "linen drawstring trousers",
        "five-pocket twill pants",
        "cuffed slim chinos",
        "drawstring linen shorts",
        "carpenter work pants",
        "double-knee utility pants"
    ],
    "outerwear": [
        "a tailored two-button blazer",
        "a classic trench coat",
        "a denim trucker jacket",
        "a wool overcoat",
        "a quilted puffer jacket",
        "a brown leather biker jacket",
        "a bomber jacket",
        "a waxed cotton field jacket",
        "a double-breasted peacoat",
        "a shearling-collar aviator jacket",
        "a harrington jacket",
        "a hooded parka",
        "a corduroy chore coat",
        "a herringbone topcoat",
        "a lightweight nylon windbreaker",
        "a suede trucker jacket"
    ],
    "formal": [
        "a navy single-breasted suit",
        "a charcoal three-piece suit",
        "a black tuxedo with satin lapels",
        "a double-breasted pinstripe suit",
        "a velvet dinner jacket",
        "a tailored morning coat",
        "a slim tuxedo with a bow tie",
        "a linen summer suit",
        "a herringbone tweed suit",
        "a white dinner jacket with black trousers",
        "a glen-check tailored suit",
        "a black tie ensemble with a cummerbund"
    ],
    "athletic": [
        "a moisture-wicking running tee",
        "a quarter-zip training pullover",
        "fitted compression base-layer tights",
        "mesh basketball shorts",
        "a sleeveless gym tank",
        "fleece-lined sweatpants",
        "a track jacket with side stripes",
        "a lightweight running windbreaker",
        "performance training shorts",
        "an oversized gym hoodie",
        "a cycling jersey",
        "a long-sleeve thermal base layer"
    ],
    "knitwear": [
        "a chunky cable-knit sweater",
        "a fine merino crewneck jumper",
        "a half-zip knit pullover",
        "a shawl-collar cardigan",
        "a ribbed turtleneck sweater",
        "a fair-isle yoke sweater",
        "a lambswool V-neck jumper",
        "a knit polo sweater",
        "a waffle-knit henley",
        "a heavy fisherman's roll-neck",
        "a button-up knit cardigan",
        "a lightweight cashmere crewneck"
    ],
    "occasion": [
        "a festive holiday knit sweater",
        "an embroidered Nehru-collar jacket",
        "a brocade smoking jacket",
        "a tailored wedding-guest suit",
        "a linen blazer for a summer party",
        "a sequined statement blazer",
        "a tropical-print short-sleeve party shirt",
        "a velvet bow-tie dinner ensemble",
        "a sharp groom's three-piece suit"
    ]
}

COLORS = [
    "black",
    "ivory",
    "off-white",
    "cream",
    "charcoal grey",
    "heather grey",
    "slate blue",
    "navy",
    "cobalt blue",
    "powder blue",
    "teal",
    "emerald green",
    "olive green",
    "sage green",
    "forest green",
    "mustard yellow",
    "ochre",
    "burnt orange",
    "terracotta",
    "rust",
    "burgundy",
    "wine red",
    "scarlet",
    "blush pink",
    "dusty rose",
    "fuchsia",
    "lavender",
    "lilac",
    "plum",
    "mauve",
    "camel",
    "tan",
    "taupe",
    "chocolate brown",
    "khaki",
    "beige",
    "champagne",
    "metallic gold",
    "silver",
    "copper",
    "coral",
    "mint green",
    "deep purple",
    "oxblood"
]

PATTERNS = [
    "solid",
    "pinstripe",
    "chalk stripe",
    "Breton stripe",
    "windowpane check",
    "tartan plaid",
    "gingham",
    "houndstooth",
    "herringbone",
    "polka dot",
    "floral print",
    "ditsy floral",
    "tropical palm print",
    "paisley",
    "animal print leopard",
    "zebra stripe",
    "snakeskin print",
    "camouflage",
    "tie-dye",
    "abstract geometric",
    "argyle",
    "fair-isle",
    "color-block",
    "ombre gradient",
    "chevron",
    "checkerboard",
    "toile de Jouy",
    "marbled print"
]

FABRICS = [
    "cotton",
    "linen",
    "silk",
    "satin",
    "denim",
    "wool",
    "cashmere",
    "merino wool",
    "tweed",
    "corduroy",
    "velvet",
    "chiffon",
    "organza",
    "lace",
    "leather",
    "faux fur",
    "suede",
    "jersey knit",
    "ribbed knit",
    "chambray",
    "tulle",
    "sequined fabric",
    "boucle",
    "shearling",
    "nylon"
]

FOOTWEAR = [
    "white leather sneakers",
    "black leather ankle boots",
    "tan suede chelsea boots",
    "strappy stiletto heels",
    "block-heel pumps",
    "pointed-toe flats",
    "leather loafers",
    "brown oxford brogues",
    "knee-high riding boots",
    "platform sandals",
    "espadrille wedges",
    "embellished evening sandals",
    "chunky combat boots",
    "ballet flats",
    "slide sandals",
    "high-top canvas sneakers",
    "patent leather derbies",
    "kitten-heel slingbacks",
    "running trainers",
    "leather gladiator sandals",
    "shearling-lined snow boots",
    "cap-toe dress shoes",
    "platform mary-janes",
    "minimalist mule heels"
]

ACCESSORIES = [
    "a wide-brim felt hat",
    "a knitted beanie",
    "a baseball cap",
    "a silk neck scarf",
    "a chunky knit scarf",
    "gold hoop earrings",
    "a layered pendant necklace",
    "a leather crossbody bag",
    "a structured tote bag",
    "a quilted shoulder bag",
    "an oversized leather belt",
    "round tortoiseshell sunglasses",
    "aviator sunglasses",
    "a leather watch",
    "stacked bangle bracelets",
    "a slim tie",
    "a patterned bow tie",
    "a pocket square",
    "leather gloves",
    "a beaded statement necklace",
    "a wide woven belt",
    "a fedora",
    "a backpack",
    "a clutch purse",
    "a silk headscarf"
]

STUDIO_BACKGROUNDS = [
    "against a seamless white studio backdrop",
    "against a seamless black backdrop",
    "against a soft gray seamless backdrop",
    "against a warm beige backdrop",
    "against a muted sage-green backdrop",
    "against a dusty pink backdrop",
    "against a deep burgundy backdrop",
    "against a rich teal backdrop",
    "against a mustard-yellow backdrop",
    "against a terracotta-toned backdrop",
    "against a cool blue studio backdrop",
    "against a smooth gradient backdrop fading from light to dark",
    "against a hand-painted mottled canvas backdrop",
    "against a textured concrete-gray backdrop",
    "against a softly lit colorama paper backdrop",
    "against a high-key pure-white backdrop",
    "against a low-key shadowed backdrop",
    "against a marbled gray-and-white backdrop"
]

REAL_SETTINGS = [
    "on a busy downtown sidewalk",
    "at a sunlit street corner",
    "in a cobblestone alley",
    "outside a corner cafe",
    "at an outdoor cafe terrace",
    "inside a cozy coffee shop",
    "on a rooftop terrace at golden hour",
    "on a rooftop overlooking the skyline",
    "in a contemporary art gallery",
    "in a sunlit museum hall",
    "at a bustling open-air market",
    "at a fresh-produce farmers market",
    "on a sandy beach at dusk",
    "along a seaside boardwalk",
    "in a corporate office lobby",
    "in an open-plan office",
    "in a quiet public library",
    "in an independent bookshop",
    "on a crowded subway platform",
    "inside a moving subway car",
    "in a lush botanical garden",
    "in a backyard flower garden",
    "in a converted industrial loft",
    "in a warehouse with exposed brick",
    "inside a boutique clothing store",
    "in a vintage record store",
    "on a wrought-iron staircase",
    "in a concrete parking garage",
    "among the rows of a vineyard",
    "in a sunlit university courtyard",
    "at a train station platform",
    "in a grand railway station hall",
    "on a forest hiking trail",
    "in a misty pine forest",
    "on a mountain overlook",
    "by a still lake at sunrise",
    "on a wooden pier over the water",
    "in a desert landscape at midday",
    "in a snowy city street",
    "on a quiet suburban street",
    "in a tiled metro underpass",
    "in a graffiti-covered backstreet",
    "on a historic stone bridge",
    "in a glass-walled greenhouse",
    "in a rooftop garden bar",
    "in a dimly lit jazz bar",
    "in a retro neon-lit diner",
    "in a minimalist white apartment",
    "in a sunlit loft kitchen",
    "in a ceramics and pottery studio",
    "in a painter's art studio",
    "in a dance rehearsal hall",
    "in a tailoring atelier",
    "in a barber shop",
    "at a poolside lounge",
    "in a luxury hotel lobby",
    "on an escalator in a shopping mall",
    "in a courtyard with climbing ivy",
    "at a waterfront promenade"
]

SITUATIONS = [
    "hailing a passing cab",
    "browsing a rack of clothes",
    "waiting in line for coffee",
    "checking a phone screen",
    "caught mid-stride while walking",
    "adjusting a shirt sleeve",
    "leaning against a doorway",
    "leaning on a railing",
    "glancing back over one shoulder",
    "stepping off a curb",
    "pausing to look up at a building",
    "carrying a folded coat over one arm",
    "sliding on a pair of sunglasses",
    "buttoning up a jacket",
    "tucking hair behind one ear",
    "checking a wristwatch",
    "flagging down a friend out of frame",
    "holding an open umbrella in the rain",
    "stepping through a revolving door",
    "pausing on a staircase landing",
    "setting down a shopping bag",
    "reaching for a book on a shelf",
    "sipping from a paper cup",
    "tying a scarf around the neck",
    "smoothing the front of a blazer",
    "shielding eyes from the sun",
    "leaning down to pet a dog out of frame",
    "waiting at a crosswalk",
    "pushing open a glass door",
    "running a hand through the hair",
    "looking out over a balcony railing",
    "crouching to adjust a shoe",
    "turning to walk away from the camera",
    "standing still in a moving crowd",
    "resting against a brick wall",
    "stretching after a long walk",
    "fastening a coat collar against the wind",
    "scrolling on a phone while seated",
    "balancing a coffee and a tote bag",
    "pausing mid-conversation off camera",
    "gazing out a rain-streaked window",
    "slipping hands into coat pockets",
    "lifting a bag onto one shoulder",
    "stepping out of a doorway into the light",
    "pausing to read a street sign",
    "adjusting the strap of a backpack",
    "looking down to check a ticket",
    "leaning forward over a cafe table",
    "pulling a jacket tighter",
    "turning a corner onto a quiet street"
]

RELATIONAL_CONTEXTS = [
    "with paper shopping bags in hand",
    "beside a parked vintage car",
    "near a vibrant flower stall",
    "amid falling autumn leaves",
    "in a crowd, in sharp focus while others blur",
    "framed by a neon storefront sign",
    "beside a wall of bold street art",
    "next to a row of potted plants",
    "under a string of cafe lights",
    "beside a glass display window with reflections",
    "amid drifting snowflakes",
    "by a fountain in a public square",
    "beside a stack of vintage suitcases",
    "near a bicycle leaning on a wall",
    "framed in an open doorway",
    "beside floor-to-ceiling windows",
    "amid steam rising from a street vent",
    "with city traffic streaking past",
    "beside a market stall of fresh fruit",
    "under a canopy of blossoming trees",
    "against a backdrop of distant city lights",
    "beside a weathered wooden fence",
    "near a coffee cart on the corner",
    "with reflections in a rain-soaked street",
    "beside an old brick archway",
    "amid hanging plants in a greenhouse",
    "next to a graffiti-tagged shutter",
    "with sunlight filtering through tall windows",
    "beside a vintage motorcycle",
    "against a mural of bright colors",
    "near a newsstand piled with magazines",
    "with a softly blurred urban background",
    "beside a stack of stacked crates",
    "under an umbrella in a light drizzle"
]

POSES = [
    "standing in a relaxed contrapposto with weight on one leg",
    "standing tall with arms at the sides",
    "walking toward the camera mid-stride",
    "walking away down a path",
    "striding confidently across the frame",
    "seated on a set of concrete steps",
    "perched on the edge of a stool",
    "sitting cross-legged on the floor",
    "leaning back against a wall with one foot propped up",
    "leaning casually against a railing",
    "leaning a shoulder against a doorframe",
    "standing with hands tucked into pockets",
    "standing with arms crossed over the chest",
    "standing with one hand on the hip",
    "standing with both hands on the hips",
    "caught mid-twirl with the skirt flaring out",
    "turning to glance back over one shoulder",
    "crouching low on the balls of the feet",
    "kneeling on one knee",
    "standing with both arms raised overhead",
    "stretching with arms reaching upward",
    "adjusting a jacket cuff",
    "buttoning a coat",
    "fixing a collar with one hand",
    "holding the lapels of an open jacket",
    "tucking a strand of hair behind one ear",
    "carrying a bag over one shoulder",
    "holding a coat slung over the shoulder",
    "mid-step while descending a staircase",
    "pausing on a stairway with one hand on the rail",
    "sitting on a bench with legs casually crossed",
    "reclining back on both hands",
    "standing with feet apart in a confident wide stance",
    "spinning so the coat swings outward",
    "tilting the head slightly while looking at the camera",
    "resting both hands behind the back",
    "shifting weight onto one hip with a relaxed lean",
    "stepping off a curb mid-motion",
    "balancing on tiptoe with arms out",
    "looking down while smoothing the front of the outfit"
]

CAMERA_ANGLES = [
    "eye-level angle",
    "low angle looking slightly up",
    "dramatic worm's-eye view from the ground",
    "high angle looking slightly down",
    "bird's-eye view from directly overhead",
    "straight-on angle",
    "slight dutch tilt",
    "three-quarter high angle",
    "three-quarter low angle",
    "chest-level angle",
    "knee-level angle looking up",
    "hip-level angle",
    "ground-level angle",
    "slightly elevated angle",
    "overhead three-quarter angle",
    "shoulder-height angle"
]

FRAMING_CROPS = [
    "full-length head-to-toe shot",
    "full-body shot showing the entire outfit",
    "full-length shot with space above and below",
    "three-quarter-length shot from the knees up",
    "cowboy shot framed from mid-thigh up",
    "wide environmental shot with the figure small in the scene",
    "head-to-toe shot with feet visible",
    "full-figure shot centered in the frame",
    "long shot showing the whole body and surroundings",
    "medium-long shot from the shins up",
    "full-body shot at a slight distance",
    "three-quarter shot from the hips up",
    "wide full-length shot with generous background",
    "establishing wide shot of the figure in the setting",
    "full-body profile shot showing the outfit's silhouette",
    "tall vertical full-length shot",
    "full-length shot with the subject filling the frame top to bottom",
    "medium shot from the waist up"
]

SUBJECT_VIEWS = [
    "front view facing the camera",
    "back view showing the rear of the outfit",
    "left profile view",
    "right profile view",
    "three-quarter turn toward the camera",
    "three-quarter turn away from the camera",
    "over-the-shoulder view looking back",
    "rear three-quarter view showing the back of the outfit",
    "front three-quarter view",
    "slightly angled front view",
    "side-on view showing the outfit's silhouette",
    "back view with the head turned to the side",
    "frontal view with a slight body twist",
    "view from behind as the subject walks away",
    "half-turned view between front and profile",
    "front view with the torso angled to one side",
    "profile view with a forward glance",
    "three-quarter back view over the shoulder"
]

POSITIONS_IN_FRAME = [
    "centered in the frame",
    "positioned on the left third of the frame",
    "positioned on the right third of the frame",
    "off-center to the left",
    "off-center to the right",
    "small within a wide frame",
    "placed low in the frame with headroom above",
    "placed high in the frame",
    "filling the frame from edge to edge",
    "set against negative space on one side",
    "anchored to the lower-left of the frame",
    "anchored to the lower-right of the frame",
    "framed slightly left of center",
    "occupying the right side with open space to the left",
    "standing at the center with symmetrical framing",
    "tucked into the bottom of a tall frame"
]

LIGHTING = [
    "soft natural daylight",
    "warm golden-hour light",
    "bright even midday light",
    "moody low-key lighting",
    "soft diffused window light",
    "overcast flat light",
    "dramatic side lighting",
    "backlit rim light",
    "cool blue-hour light",
    "warm tungsten indoor light",
    "dappled light filtering through leaves",
    "neon-tinted ambient light",
    "soft studio lighting with a large softbox",
    "high-key bright studio light",
    "directional hard light casting crisp shadows",
    "gentle overhead lighting",
    "split lighting across the face and body",
    "warm sunset glow from one side"
]

WHITEBG_STRIP = [
    "in front of a white background",
    "in front of a plain white background",
    "in front of a plain background",
    "on a white background",
    "against a white background",
    "against a plain white background",
    "against a plain white backdrop",
    "against a plain backdrop",
    "on a plain white backdrop",
    "in front of a white backdrop",
    "studio white background",
    "white studio background",
    "isolated on a white background",
    "against a seamless white backdrop",
    "on a solid white background"
]

FASHION_QUALITY = [
    "full-length realistic color fashion photograph, the entire outfit visible from head to toe",
    "professional color full-body fashion editorial photo, head-to-toe framing, footwear visible",
    "photorealistic full-length color photograph, complete outfit shown including shoes",
    "high-quality color fashion photography, full figure in frame, sharp detail on fabric and footwear",
    "realistic color lookbook photo, full body composition, natural skin tones and accurate garment color",
    "editorial color fashion shot, whole standing figure framed head to toe, crisp focus",
    "color full-body street-style photograph, complete head-to-toe outfit, realistic textures",
    "professional color photograph of the full ensemble, shoes and silhouette fully visible",
    "realistic color catalog photo, full-length pose, true-to-life fabric colors and clean detail",
    "photorealistic color fashion image, whole outfit rendered, balanced lighting, full figure shown",
    "high-resolution color full-body fashion portrait, head-to-toe, accurate garment and footwear color",
    "natural color full-length photograph, the complete look visible from hair to shoes, fine detail"
]

FASHION_AMATEUR = [
    "amateur color full-body snapshot, slightly soft focus, casual lighting, full outfit still visible",
    "candid color phone photo of the whole outfit head to toe, everyday lighting, mild grain",
    "casual amateur full-length color photograph, imperfect framing, complete look in frame",
    "everyday color point-and-shoot full-body snapshot, simple lighting, slight noise, outfit visible head to toe",
    "amateur color mirror-style full-length photo, plain indoor lighting, whole outfit shown",
    "casual color snapshot of the full ensemble, slightly uneven framing, realistic everyday look"
]

FEMALE_RARE_EMPHASIS = [
    "dresses (day, cocktail, evening, maxi, midi, slip, wrap, shirt dress)",
    "formal gowns and ball gowns",
    "women's tailored suits and pantsuits",
    "blazers and structured jackets",
    "outerwear (trench coats, wool coats, peacoats, puffer jackets, capes)",
    "jumpsuits and rompers",
    "skirt suits and matching co-ord sets",
    "knitwear (cardigans, turtlenecks, sweater dresses)",
    "traditional and cultural formalwear (sari, hanbok, cheongsam, kimono, abaya)",
    "tailored trousers with blouses",
    "leather and statement jackets",
    "professional and business attire",
    "winter layering ensembles",
    "athleisure and activewear sets"
]

